version: '2'
services:
  fwblog-app:
    image: fwblog
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fwblog-postgresql:5432/fwblog
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  fwblog-postgresql:
    extends:
      file: postgresql.yml
      service: fwblog-postgresql
